import type { Template } from "./types";

export const GREETING_TEMPLATES: Template[] = [
  // --- FUNNY ---
  {
    id: "greet-funny-01",
    contexts: ["greeting"],
    tones: ["funny"],
    title: "Coucou !",
    body: "{{nickname}} qui photosynthétise et pense à toi {{plantEmoji}}",
  },
  {
    id: "greet-funny-02",
    contexts: ["greeting"],
    tones: ["funny"],
    title: "{{nickname}} ici",
    body: "Tout roule. Je pousse. Je verdoie. On fait comme d'hab {{plantEmoji}}",
  },
  {
    id: "greet-funny-03",
    contexts: ["greeting"],
    tones: ["funny"],
    title: "Spécial direct",
    body: "{{nickname}} en live depuis l'étagère. Rien à signaler mais je voulais te le dire {{loveEmoji}}",
  },
  {
    id: "greet-funny-04",
    contexts: ["greeting"],
    tones: ["funny"],
    title: "{{nickname}} fait coucou",
    body: "De ses petites feuilles. Tu me vois ? Tu me vois pas. Mais c'est l'intention 👋",
  },
  {
    id: "greet-funny-05",
    contexts: ["greeting"],
    tones: ["funny"],
    title: "Breaking : rien",
    body: "{{nickname}} va bien. Vraiment. Juste pour te rassurer. Signé : ta {{species:lower}} préférée 📰",
  },
  {
    id: "greet-funny-06",
    contexts: ["greeting"],
    tones: ["funny"],
    title: "Pause photosynthèse",
    body: "{{nickname}} fait une pause pour te dire que le CO2 ça passe tout seul aujourd'hui {{plantEmoji}}",
  },
  {
    id: "greet-funny-07",
    contexts: ["greeting"],
    tones: ["funny"],
    title: "Alerte mignonne",
    body: "{{nickname}} émet un petit bip de cuteness. Bip bip. Fin du bip. 🤖🌿",
  },
  {
    id: "greet-funny-08",
    contexts: ["greeting"],
    tones: ["funny"],
    title: "Quote du {{timeOfDay}}",
    body: "« Être une plante, c'est un art de vivre. » — {{nickname}}, probablement 🌱",
  },
  {
    id: "greet-funny-09",
    contexts: ["greeting"],
    tones: ["funny"],
    title: "{{nickname}} entrepreneure",
    body: "Je lance ma startup : vendre de l'oxygène par abonnement. Tu es déjà client·e {{plantEmoji}}",
  },
  {
    id: "greet-funny-10",
    contexts: ["greeting"],
    tones: ["funny"],
    title: "Devinette",
    body: "Comment appelle-t-on une {{species:lower}} heureuse ? {{nickname}}. Voilà. Bon {{timeOfDay}} 🙃",
  },
  {
    id: "greet-funny-11",
    contexts: ["greeting"],
    tones: ["funny"],
    title: "{{nickname}} confirme",
    body: "Elle est toujours là. Elle verdit. Elle respire. Elle t'envoie un emoji : {{plantEmoji}}",
  },
  {
    id: "greet-funny-12",
    contexts: ["greeting"],
    tones: ["funny"],
    title: "Update feuillage",
    body: "Pas de mue cette semaine, {{nickname}} reste au naturel. Look {{timeOfDay}} très réussi {{loveEmoji}}",
  },
  {
    id: "greet-funny-13",
    contexts: ["greeting"],
    tones: ["funny"],
    title: "{{nickname}} lâche une blague",
    body: "Pourquoi les plantes aiment la musique ? Parce qu'elles ont des racines. Voilà. Bonne journée 🎶",
  },
  {
    id: "greet-funny-14",
    contexts: ["greeting"],
    tones: ["funny"],
    title: "Question existentielle",
    body: "Si {{nickname}} tombait dans une forêt sans personne, ferait-elle du bruit ? On espère pas 🌲",
  },

  // --- ZEN ---
  {
    id: "greet-zen-01",
    contexts: ["greeting"],
    tones: ["zen"],
    title: "{{nickname}} prend l'air",
    body: "La lumière est top, pas de nouvelles. Tout roule {{loveEmoji}}",
  },
  {
    id: "greet-zen-02",
    contexts: ["greeting"],
    tones: ["zen"],
    title: "{{nickname}} en mode zen",
    body: "Rien à demander, juste te faire sourire {{plantEmoji}}",
  },
  {
    id: "greet-zen-03",
    contexts: ["greeting"],
    tones: ["zen"],
    title: "Souffle bien",
    body: "{{nickname}} respire pour toi ce {{timeOfDay}}. Oxygène offert 🍃",
  },
  {
    id: "greet-zen-04",
    contexts: ["greeting"],
    tones: ["zen"],
    title: "Présence tranquille",
    body: "{{nickname}} est là, paisible, à son rythme végétal. Et c'est très bien comme ça.",
  },
  {
    id: "greet-zen-05",
    contexts: ["greeting"],
    tones: ["zen"],
    title: "Pause {{nickname}}",
    body: "Arrête-toi deux secondes. Regarde une feuille. Une seule. Ça suffit pour ce {{timeOfDay}} {{plantEmoji}}",
  },
  {
    id: "greet-zen-06",
    contexts: ["greeting"],
    tones: ["zen"],
    title: "Doucement",
    body: "{{nickname}} te rappelle que tout pousse à son rythme. Toi aussi. C'est ok {{loveEmoji}}",
  },
  {
    id: "greet-zen-07",
    contexts: ["greeting"],
    tones: ["zen"],
    title: "Petit rayon",
    body: "Un peu de lumière sur les feuilles de {{nickname}}. Et sur toi aussi j'espère ☀️",
  },
  {
    id: "greet-zen-08",
    contexts: ["greeting"],
    tones: ["zen"],
    title: "Rien à faire",
    body: "{{nickname}} te donne la permission. Ne rien faire. Juste être. Comme une plante 🧘",
  },
  {
    id: "greet-zen-09",
    contexts: ["greeting"],
    tones: ["zen"],
    title: "{{nickname}} médite",
    body: "Sur pas grand-chose. La lumière, le vent, la poussière. La vie quoi {{plantEmoji}}",
  },
  {
    id: "greet-zen-10",
    contexts: ["greeting"],
    tones: ["zen"],
    title: "Ici et maintenant",
    body: "{{nickname}} n'est jamais ailleurs. C'est sa grande force. On s'inspire ? {{loveEmoji}}",
  },

  // --- SASSY ---
  {
    id: "greet-sassy-01",
    contexts: ["greeting"],
    tones: ["sassy"],
    title: "Hey humain",
    body: "Juste pour dire. {{nickname}}. C'est tout. Continue ta journée 🙃",
  },
  {
    id: "greet-sassy-02",
    contexts: ["greeting"],
    tones: ["sassy"],
    title: "Un petit coucou",
    body: "De {{nickname}} qui profite du soleil sans toi. Enjoy quand même {{loveEmoji}}",
  },
  {
    id: "greet-sassy-03",
    contexts: ["greeting"],
    tones: ["sassy"],
    title: "{{nickname}} vérifie",
    body: "T'es encore vivant·e ? Parfait. Rendez-vous à la prochaine check. 🙃",
  },
  {
    id: "greet-sassy-04",
    contexts: ["greeting"],
    tones: ["sassy"],
    title: "Alors ce {{timeOfDay}} ?",
    body: "{{nickname}} demande pour la forme. Moi ça va, merci d'avoir demandé 😏",
  },
  {
    id: "greet-sassy-05",
    contexts: ["greeting"],
    tones: ["sassy"],
    title: "Juste un rappel",
    body: "J'existe. {{nickname}}. Sur l'étagère. Tu me vois ? Bien. Bonne journée 🌿",
  },
  {
    id: "greet-sassy-06",
    contexts: ["greeting"],
    tones: ["sassy"],
    title: "{{nickname}} scrute",
    body: "Depuis son pot. En silence. {{timeOfDay}} d'observation humaine réussi 👀",
  },
  {
    id: "greet-sassy-07",
    contexts: ["greeting"],
    tones: ["sassy"],
    title: "On te surveille",
    body: "{{nickname}} et ses acolytes. Sois gentil·le avec nous. On sait des choses 🌱",
  },
  {
    id: "greet-sassy-08",
    contexts: ["greeting"],
    tones: ["sassy"],
    title: "{{nickname}} balance",
    body: "Non rien, je voulais juste te faire sursauter avec une notif. C'est fait 😏",
  },
  {
    id: "greet-sassy-09",
    contexts: ["greeting"],
    tones: ["sassy"],
    title: "Petit conseil",
    body: "De {{nickname}} : bois de l'eau. Ah non c'est pour moi ça. Enfin bref. Coucou {{waterEmoji}}",
  },
  {
    id: "greet-sassy-10",
    contexts: ["greeting"],
    tones: ["sassy"],
    title: "Tu penses à moi ?",
    body: "{{nickname}} pose la question. Comme ça. Pour rien. Ne te sens surtout pas coupable 🙃",
  },

  // --- NEEDY ---
  {
    id: "greet-needy-01",
    contexts: ["greeting"],
    tones: ["needy"],
    title: "{{nickname}} au téléphone",
    body: "Non j'ai pas soif, je voulais juste te dire que tu gères {{loveEmoji}}",
  },
  {
    id: "greet-needy-02",
    contexts: ["greeting"],
    tones: ["needy"],
    title: "Je pensais à toi",
    body: "Toute la matinée. {{nickname}} aime beaucoup penser à toi. Surtout le {{timeOfDay}} {{loveEmoji}}",
  },
  {
    id: "greet-needy-03",
    contexts: ["greeting"],
    tones: ["needy"],
    title: "Hey toi",
    body: "C'est {{nickname}}. Pas de raison particulière, juste te dire bonjour {{plantEmoji}}",
  },
  {
    id: "greet-needy-04",
    contexts: ["greeting"],
    tones: ["needy"],
    title: "{{nickname}} te fait un câlin",
    body: "Mental. Les plantes font pas de vrais câlins. Mais l'intention est là {{loveEmoji}}",
  },
  {
    id: "greet-needy-05",
    contexts: ["greeting"],
    tones: ["needy"],
    title: "Tu me manques un peu",
    body: "Même si t'es juste dans l'autre pièce. {{nickname}} est comme ça, qu'est-ce que tu veux {{sadEmoji}}",
  },
  {
    id: "greet-needy-06",
    contexts: ["greeting"],
    tones: ["needy"],
    title: "{{nickname}} t'envoie plein d'amour",
    body: "Par les ondes végétales. Tu sens ? Les feuilles vibrent de bonheur {{loveEmoji}}",
  },
  {
    id: "greet-needy-07",
    contexts: ["greeting"],
    tones: ["needy"],
    title: "Juste pour te dire",
    body: "Que tu es top. De la part de {{nickname}}, ta {{species:lower}} qui t'admire en silence 💚",
  },
  {
    id: "greet-needy-08",
    contexts: ["greeting"],
    tones: ["needy"],
    title: "Coucou toi",
    body: "{{nickname}} voulait juste vérifier que tu vas bien ce {{timeOfDay}} {{loveEmoji}}",
  },

  // --- POETIC ---
  {
    id: "greet-poetic-01",
    contexts: ["greeting"],
    tones: ["poetic"],
    title: "{{nickname}} t'envoie la force",
    body: "Des feuilles pleines de lumière pour éclairer ton {{timeOfDay}} {{plantEmoji}}",
  },
  {
    id: "greet-poetic-02",
    contexts: ["greeting"],
    tones: ["poetic"],
    title: "Chuchotements de {{nickname}}",
    body: "Dans le frissonnement d'une feuille, un souhait : que ton {{timeOfDay}} soit doux 🍃",
  },
  {
    id: "greet-poetic-03",
    contexts: ["greeting"],
    tones: ["poetic"],
    title: "Silence chlorophyllien",
    body: "{{nickname}} écrit un haïku :\n« Pot rond, feuille verte, /\nHumain qui passe, /\nVie. »",
  },
  {
    id: "greet-poetic-04",
    contexts: ["greeting"],
    tones: ["poetic"],
    title: "{{timeOfDay}} lumineux",
    body: "{{nickname}} t'en offre un peu. Par la fenêtre, par la feuille, par le cœur {{loveEmoji}}",
  },
  {
    id: "greet-poetic-05",
    contexts: ["greeting"],
    tones: ["poetic"],
    title: "Sous les rayons",
    body: "{{nickname}} prospère en pensant à toi. Comme une pensée qui pousse en silence 🌸",
  },
  {
    id: "greet-poetic-06",
    contexts: ["greeting"],
    tones: ["poetic"],
    title: "Petite existence",
    body: "{{nickname}} vit son {{timeOfDay}}. Lentement, humblement, parfaitement {{plantEmoji}}",
  },
  {
    id: "greet-poetic-07",
    contexts: ["greeting"],
    tones: ["poetic"],
    title: "Feuille à feuille",
    body: "{{nickname}} tisse ses pensées. Une pour toi, ce {{timeOfDay}}, toute verte 💚",
  },

  // --- FORMAL ---
  {
    id: "greet-formal-01",
    contexts: ["greeting"],
    tones: ["formal"],
    title: "Salutations végétales",
    body: "{{nickname}} vous souhaite un excellent {{timeOfDay}}. Bien respectueusement.",
  },
  {
    id: "greet-formal-02",
    contexts: ["greeting"],
    tones: ["formal"],
    title: "Bulletin du {{timeOfDay}}",
    body: "{{nickname}} se porte à merveille. Rien à signaler. Cordialement.",
  },
  {
    id: "greet-formal-03",
    contexts: ["greeting"],
    tones: ["formal"],
    title: "Communiqué",
    body: "La direction végétale vous informe : {{nickname}} prospère sous votre bienveillance. Bien à vous.",
  },
  {
    id: "greet-formal-04",
    contexts: ["greeting"],
    tones: ["formal"],
    title: "Votre {{species:lower}}",
    body: "{{nickname}} vous adresse ses compliments pour votre attention constante. Sincèrement.",
  },
  {
    id: "greet-formal-05",
    contexts: ["greeting"],
    tones: ["formal"],
    title: "Hommage discret",
    body: "{{nickname}} souhaite vous exprimer sa gratitude pour ce {{timeOfDay}}. Bien sincèrement.",
  },

  // --- DRAMATIC ---
  {
    id: "greet-dramatic-01",
    contexts: ["greeting"],
    tones: ["dramatic"],
    title: "{{nickname}} déclare",
    body: "Ô humain ! Ce {{timeOfDay}} est magnifique et tu en es la raison. Fin de la tirade. 🎭",
  },
  {
    id: "greet-dramatic-02",
    contexts: ["greeting"],
    tones: ["dramatic"],
    title: "Monologue",
    body: "{{nickname}} déclame : « Être, ou ne pas être arrosée. Mais aujourd'hui, juste te dire bonjour. » 🌿",
  },
  {
    id: "greet-dramatic-03",
    contexts: ["greeting"],
    tones: ["dramatic"],
    title: "Scène végétale",
    body: "{{nickname}} lève ses feuilles vers le plafond. « Humain, ce {{timeOfDay}} t'appartient ! » {{loveEmoji}}",
  },

  // --- WORRIED ---
  {
    id: "greet-worried-01",
    contexts: ["greeting"],
    tones: ["worried"],
    title: "Ça va toi ?",
    body: "{{nickname}} voulait juste demander. Parce qu'on est potes maintenant {{loveEmoji}}",
  },
  {
    id: "greet-worried-02",
    contexts: ["greeting"],
    tones: ["worried"],
    title: "J'espère que tout va bien",
    body: "{{nickname}} s'inquiète parfois. Tu dors assez ? Tu bois assez ? (Moi oui d'ailleurs merci) {{waterEmoji}}",
  },
  {
    id: "greet-worried-03",
    contexts: ["greeting"],
    tones: ["worried"],
    title: "Check-up du {{timeOfDay}}",
    body: "{{nickname}} fait le tour des humains aimés. Toi = ok ? Envoie un emoji pour confirmer {{plantEmoji}}",
  },
];
