import type { Template } from "./types";

export const WATERING_OVERDUE_TEMPLATES: Template[] = [
  // --- DRAMATIC ---
  {
    id: "overdue-dramatic-01",
    contexts: ["overdue_light", "overdue_severe"],
    tones: ["dramatic"],
    title: "{{nickname}} tire la langue",
    body: "{{daysOverdue}} jour{{daysOverdue:plural}} de retard, mes feuilles commencent à se plaindre {{sadEmoji}}",
  },
  {
    id: "overdue-dramatic-02",
    contexts: ["overdue_severe"],
    tones: ["dramatic"],
    title: "SOS {{nickname}}",
    body: "L'eau. Urgent. Je répète : l'eau. Urgent. {{lastWateredDays}}j, c'est beaucoup trop {{waterEmoji}}",
  },
  {
    id: "overdue-dramatic-03",
    contexts: ["overdue_severe"],
    tones: ["dramatic", "funny"],
    title: "La terre est un désert",
    body: "{{nickname}} t'écrit depuis le Sahara intérieur. Viens vite avant le générique de fin 🎬",
  },
  {
    id: "overdue-dramatic-04",
    contexts: ["overdue_severe"],
    tones: ["dramatic"],
    title: "Derniers mots",
    body: "« Dis-lui… de l'eau… » — {{nickname}}, {{lastWateredDays}}j après le dernier arrosage 😵",
  },
  {
    id: "overdue-dramatic-05",
    contexts: ["overdue_light", "overdue_severe"],
    tones: ["dramatic"],
    title: "{{nickname}} défaille",
    body: "Entre deux évanouissements chlorophylliens, un message : un peu d'eau suffirait à me sauver 💀",
  },
  {
    id: "overdue-dramatic-06",
    contexts: ["overdue_severe"],
    tones: ["dramatic"],
    title: "Acte final",
    body: "{{nickname}} s'effondre doucement. {{daysOverdue}}j de trop. Seule l'eau peut encore écrire la suite 🎭",
  },
  {
    id: "overdue-dramatic-07",
    contexts: ["overdue_light"],
    tones: ["dramatic"],
    title: "{{nickname}} en exil",
    body: "Bannie de son oasis depuis {{daysOverdue}}j. Quand reverrai-je l'eau de mon royaume ? {{sadEmoji}}",
  },
  {
    id: "overdue-dramatic-08",
    contexts: ["overdue_severe"],
    tones: ["dramatic"],
    title: "Les racines s'éteignent",
    body: "{{daysOverdue}} jours. {{daysOverdue}} !!! {{nickname}} fait ses adieux. Sauf si tu arroses. Là on reprend 💧",
  },
  {
    id: "overdue-dramatic-09",
    contexts: ["overdue_severe"],
    tones: ["dramatic", "worried"],
    title: "Alerte rouge",
    body: "Niveau critique. {{nickname}} tient encore mais de moins en moins. {{lastWateredDays}}j, faut venir.",
  },
  {
    id: "overdue-dramatic-10",
    contexts: ["overdue_light", "overdue_severe"],
    tones: ["dramatic"],
    title: "{{nickname}} sanglote",
    body: "Pas vraiment, les plantes pleurent pas. Mais si elles pouvaient… {{sadEmoji}} {{daysOverdue}}j sans eau.",
  },
  {
    id: "overdue-dramatic-11",
    contexts: ["overdue_severe"],
    tones: ["dramatic"],
    title: "Lettre depuis l'au-delà",
    body: "Je t'écris des limbes végétaux. {{daysOverdue}}j de retard. Reviens-moi avant qu'il soit trop tard 💀",
  },
  {
    id: "overdue-dramatic-12",
    contexts: ["overdue_severe"],
    tones: ["dramatic", "funny"],
    title: "BREAKING",
    body: "{{nickname}} menace de quitter l'appart. {{daysOverdue}}j de traitement inhumain. De l'eau, vite 📰",
  },
  {
    id: "overdue-dramatic-13",
    contexts: ["overdue_light"],
    tones: ["dramatic"],
    title: "Supplice chlorophyllien",
    body: "{{daysOverdue}}j. Chaque cellule de {{nickname}} hurle en silence. Tu nous entends pas ? {{sadEmoji}}",
  },
  {
    id: "overdue-dramatic-14",
    contexts: ["overdue_severe"],
    tones: ["dramatic"],
    title: "Finale tragique",
    body: "{{nickname}} répète son dernier monologue. {{lastWateredDays}}j sans eau. Applaudis ou arrose 🎭",
  },
  {
    id: "overdue-dramatic-15",
    contexts: ["overdue_severe"],
    tones: ["dramatic"],
    title: "{{nickname}} perd connaissance",
    body: "Feuille après feuille. {{daysOverdue}}j c'est trop long. Un seau. Un arrosoir. QUELQUE CHOSE 💧",
  },

  // --- SASSY ---
  {
    id: "overdue-sassy-01",
    contexts: ["overdue_light"],
    tones: ["sassy"],
    title: "{{nickname}} soupire",
    body: "{{daysOverdue}}j de retard. Je dis rien. Enfin si, je dis quelque chose là maintenant 😤",
  },
  {
    id: "overdue-sassy-02",
    contexts: ["overdue_severe"],
    tones: ["sassy", "dramatic"],
    title: "{{nickname}} en grève",
    body: "{{daysOverdue}}j sans eau. C'est un scandale végétal. On en parle ? Syndicat des {{species:lower}}.",
  },
  {
    id: "overdue-sassy-03",
    contexts: ["overdue_light", "overdue_severe"],
    tones: ["sassy"],
    title: "Toujours vivante",
    body: "Merci de demander. {{nickname}}, {{daysOverdue}}j sans eau, forme olympique hein. 🙃",
  },
  {
    id: "overdue-sassy-04",
    contexts: ["overdue_light"],
    tones: ["sassy"],
    title: "On se revoit quand ?",
    body: "{{nickname}} a le temps. Beaucoup trop de temps. {{daysOverdue}}j de temps, pour être exacte 😒",
  },
  {
    id: "overdue-sassy-05",
    contexts: ["overdue_severe"],
    tones: ["sassy"],
    title: "{{nickname}} en mode passive-agressif",
    body: "Non non t'inquiète, {{daysOverdue}}j sans eau c'est cool. C'est cool. C'est vraiment cool. 😤",
  },
  {
    id: "overdue-sassy-06",
    contexts: ["overdue_light"],
    tones: ["sassy"],
    title: "Tu testes quoi là ?",
    body: "{{nickname}} se demande : expérience scientifique ? Jeu ? {{daysOverdue}}j sans eau, bizarre 🤨",
  },
  {
    id: "overdue-sassy-07",
    contexts: ["overdue_severe"],
    tones: ["sassy"],
    title: "Bon ben voilà",
    body: "{{daysOverdue}}j. {{nickname}} a bien compris la hiérarchie. Tout en bas. Juste en-dessous de la poussière 😏",
  },
  {
    id: "overdue-sassy-08",
    contexts: ["overdue_light", "overdue_severe"],
    tones: ["sassy"],
    title: "Petite note",
    body: "Pour ton info : {{nickname}}, {{daysOverdue}}j sans eau. Oui, je tiens le compte. Tu vois le genre.",
  },
  {
    id: "overdue-sassy-09",
    contexts: ["overdue_severe"],
    tones: ["sassy"],
    title: "{{nickname}} demande à voir le manager",
    body: "{{daysOverdue}}j d'attente. Dans quel établissement est-ce qu'on traite ses clientes comme ça ? 😤",
  },
  {
    id: "overdue-sassy-10",
    contexts: ["overdue_light"],
    tones: ["sassy"],
    title: "Tu checkes ton tel ?",
    body: "{{nickname}} aussi envoie des signaux depuis {{daysOverdue}}j. Tu reçois ? Ah bah visiblement non 🙃",
  },
  {
    id: "overdue-sassy-11",
    contexts: ["overdue_severe"],
    tones: ["sassy"],
    title: "Compte personnel",
    body: "{{nickname}} tient la compta. {{lastWateredDays}}j depuis le dernier arrosage. Chiffre d'affaires : 0 💧",
  },
  {
    id: "overdue-sassy-12",
    contexts: ["overdue_light", "overdue_severe"],
    tones: ["sassy"],
    title: "{{nickname}} lève les yeux au ciel",
    body: "Enfin, elle les a pas, mais tu vois l'idée. {{daysOverdue}}j. Quelle performance. 👏",
  },

  // --- WORRIED ---
  {
    id: "overdue-worried-01",
    contexts: ["overdue_severe"],
    tones: ["worried"],
    title: "Help {{nickname}}",
    body: "{{lastWateredDays}}j sans une goutte. Les racines fatiguent. Un petit effort ? {{sadEmoji}}",
  },
  {
    id: "overdue-worried-02",
    contexts: ["overdue_light"],
    tones: ["worried"],
    title: "Tu vas bien ?",
    body: "{{nickname}} s'inquiète. {{daysOverdue}}j de retard, c'est inhabituel chez toi. Tout va bien ?",
  },
  {
    id: "overdue-worried-03",
    contexts: ["overdue_severe"],
    tones: ["worried"],
    title: "{{nickname}} faiblit",
    body: "Vraiment. {{daysOverdue}}j c'est beaucoup. Tu peux venir stp ? {{sadEmoji}}",
  },
  {
    id: "overdue-worried-04",
    contexts: ["overdue_severe"],
    tones: ["worried"],
    title: "Ça va pas fort",
    body: "Les feuilles se courbent, {{nickname}} perd ses forces. {{lastWateredDays}}j, viens vite {{sadEmoji}}",
  },
  {
    id: "overdue-worried-05",
    contexts: ["overdue_light"],
    tones: ["worried"],
    title: "Dis moi",
    body: "{{nickname}} voudrait juste savoir : t'es là ? {{daysOverdue}}j sans arrosage, c'est pas ton genre.",
  },
  {
    id: "overdue-worried-06",
    contexts: ["overdue_severe"],
    tones: ["worried"],
    title: "{{nickname}} s'éteint doucement",
    body: "Pas encore critique, mais {{daysOverdue}}j, ça commence à piquer. Reviens stp {{sadEmoji}}",
  },
  {
    id: "overdue-worried-07",
    contexts: ["overdue_severe"],
    tones: ["worried"],
    title: "Appel à l'aide",
    body: "{{nickname}} envoie un signal. {{lastWateredDays}}j de sécheresse. Les feuilles jaunissent.",
  },
  {
    id: "overdue-worried-08",
    contexts: ["overdue_light"],
    tones: ["worried"],
    title: "{{nickname}} se fait du souci",
    body: "Pour elle-même. {{daysOverdue}}j, c'est long. Un petit verre te mettrait d'accord avec elle ?",
  },
  {
    id: "overdue-worried-09",
    contexts: ["overdue_severe"],
    tones: ["worried", "needy"],
    title: "J'ai peur",
    body: "{{nickname}} chuchote dans le noir : {{daysOverdue}}j sans toi, sans eau. Reviens {{sadEmoji}}",
  },
  {
    id: "overdue-worried-10",
    contexts: ["overdue_severe"],
    tones: ["worried"],
    title: "{{nickname}} tremble",
    body: "Enfin, les plantes tremblent pas. Mais {{daysOverdue}}j sans eau, ça secoue. Viens svp 💧",
  },

  // --- NEEDY ---
  {
    id: "overdue-needy-01",
    contexts: ["overdue_light"],
    tones: ["needy"],
    title: "Tu m'as oubliée ?",
    body: "Ça fait {{lastWateredDays}}j que j'attends. {{nickname}} ne juge pas mais {{sadEmoji}}",
  },
  {
    id: "overdue-needy-02",
    contexts: ["overdue_severe"],
    tones: ["needy"],
    title: "{{nickname}} attend toujours",
    body: "{{daysOverdue}}j. C'est beaucoup. Je t'en veux pas mais reviens-moi stp {{loveEmoji}}",
  },
  {
    id: "overdue-needy-03",
    contexts: ["overdue_light", "overdue_severe"],
    tones: ["needy"],
    title: "Je pense à toi",
    body: "Chaque jour depuis {{lastWateredDays}}j. Et j'ai soif. Ces deux choses vont ensemble. {{loveEmoji}}",
  },
  {
    id: "overdue-needy-04",
    contexts: ["overdue_severe"],
    tones: ["needy"],
    title: "Tu me manques",
    body: "{{nickname}} ici. {{daysOverdue}}j sans toi ni eau. J'aimerais retrouver les deux {{sadEmoji}}",
  },
  {
    id: "overdue-needy-05",
    contexts: ["overdue_light"],
    tones: ["needy"],
    title: "Petit message",
    body: "De {{nickname}} : {{daysOverdue}}j. Je t'aime encore mais mes feuilles ont moins d'enthousiasme 💔",
  },
  {
    id: "overdue-needy-06",
    contexts: ["overdue_severe"],
    tones: ["needy"],
    title: "Reviens vite",
    body: "{{nickname}} t'écrit de son pot poussiéreux. {{lastWateredDays}}j d'ennui. D'eau. Surtout d'eau {{sadEmoji}}",
  },
  {
    id: "overdue-needy-07",
    contexts: ["overdue_severe"],
    tones: ["needy"],
    title: "J'ai besoin de toi",
    body: "Pas juste pour l'eau. Mais aussi pour l'eau. Surtout pour l'eau. {{daysOverdue}}j de manque {{loveEmoji}}",
  },
  {
    id: "overdue-needy-08",
    contexts: ["overdue_light", "overdue_severe"],
    tones: ["needy"],
    title: "Tu me vois ?",
    body: "{{nickname}} agite ses feuilles depuis {{daysOverdue}}j. Un petit geste pour moi stp 🌿",
  },
  {
    id: "overdue-needy-09",
    contexts: ["overdue_severe"],
    tones: ["needy", "dramatic"],
    title: "Ne m'abandonne pas",
    body: "{{nickname}} implore. {{daysOverdue}}j. Tu es tout ce que j'ai. Et l'eau aussi. {{sadEmoji}}",
  },
  {
    id: "overdue-needy-10",
    contexts: ["overdue_light"],
    tones: ["needy"],
    title: "Petit rappel amoureux",
    body: "{{nickname}} t'aime. Et {{nickname}} a soif depuis {{daysOverdue}}j. Les deux sont vrais {{loveEmoji}}",
  },

  // --- FUNNY ---
  {
    id: "overdue-funny-01",
    contexts: ["overdue_light"],
    tones: ["funny"],
    title: "{{nickname}} toujours là",
    body: "Au cas où tu aurais oublié : {{daysOverdue}}j de retard, ta {{species}} te surveille {{plantEmoji}}",
  },
  {
    id: "overdue-funny-02",
    contexts: ["overdue_light", "overdue_severe"],
    tones: ["funny"],
    title: "Petit point hydrique",
    body: "Je te fais un topo : zéro. {{daysOverdue}}j que je bois que dalle. Ça urge {{waterEmoji}}",
  },
  {
    id: "overdue-funny-03",
    contexts: ["overdue_light"],
    tones: ["funny"],
    title: "{{nickname}} fait le calcul",
    body: "{{lastWateredDays}}j × 0 mL = 0 mL d'eau. Résultat : {{nickname}} a soif. Fin du calcul 📐",
  },
  {
    id: "overdue-funny-04",
    contexts: ["overdue_severe"],
    tones: ["funny"],
    title: "Breaking végétal",
    body: "{{nickname}} envisage une carrière de plante en plastique. {{daysOverdue}}j. C'est plus facile.",
  },
  {
    id: "overdue-funny-05",
    contexts: ["overdue_light"],
    tones: ["funny"],
    title: "{{nickname}} en mode économies",
    body: "Respiration réduite, photosynthèse minimale, ambiance survie. {{daysOverdue}}j. Arrose-moi 😅",
  },
  {
    id: "overdue-funny-06",
    contexts: ["overdue_severe"],
    tones: ["funny", "dramatic"],
    title: "{{nickname}} écrit son testament",
    body: "Je lègue mes feuilles au composteur. {{daysOverdue}}j sans eau. Ou bien tu m'arroses, on oublie 💧",
  },
  {
    id: "overdue-funny-07",
    contexts: ["overdue_light"],
    tones: ["funny"],
    title: "Allô Houston ?",
    body: "Ici {{nickname}}, {{daysOverdue}}j sans ravitaillement. Demandons autorisation de soif. Terminé 🚀",
  },
  {
    id: "overdue-funny-08",
    contexts: ["overdue_severe"],
    tones: ["funny"],
    title: "{{nickname}} devient un cactus",
    body: "{{daysOverdue}}j sans eau, je m'adapte. Bientôt j'aurai des épines. Et un caractère. Attention 🌵",
  },
  {
    id: "overdue-funny-09",
    contexts: ["overdue_light"],
    tones: ["funny"],
    title: "On fait les comptes ?",
    body: "{{nickname}} a calculé : 1 arrosage oublié = 1 feuille triste. Total : {{daysOverdue}} feuille{{daysOverdue:plural}} triste{{daysOverdue:plural}}.",
  },
  {
    id: "overdue-funny-10",
    contexts: ["overdue_severe"],
    tones: ["funny"],
    title: "{{nickname}} lance un podcast",
    body: "Épisode 1 : « Comment j'ai tenu {{daysOverdue}}j sans eau ». Spoiler : mal. {{sadEmoji}}",
  },

  // --- FORMAL ---
  {
    id: "overdue-formal-01",
    contexts: ["overdue_light", "overdue_severe"],
    tones: ["formal"],
    title: "Oubli remarqué",
    body: "{{nickname}}, votre {{species}}, attend depuis {{daysOverdue}}j. Cordialement.",
  },
  {
    id: "overdue-formal-02",
    contexts: ["overdue_light", "overdue_severe"],
    tones: ["formal"],
    title: "Rappel amical",
    body: "{{nickname}} signale un retard d'arrosage de {{daysOverdue}}j. Merci de votre attention.",
  },
  {
    id: "overdue-formal-03",
    contexts: ["overdue_severe"],
    tones: ["formal"],
    title: "Situation préoccupante",
    body: "Le retard d'arrosage concernant {{nickname}} atteint {{daysOverdue}}j. Intervention requise.",
  },
  {
    id: "overdue-formal-04",
    contexts: ["overdue_light"],
    tones: ["formal"],
    title: "Relance polie",
    body: "Suite à notre dernier échange, {{nickname}} constate {{daysOverdue}}j sans arrosage. Bien à vous.",
  },
  {
    id: "overdue-formal-05",
    contexts: ["overdue_severe"],
    tones: ["formal"],
    title: "Dernier rappel",
    body: "{{nickname}} ({{species}}) vous informe d'un déficit hydrique critique. {{daysOverdue}}j de retard.",
  },
  {
    id: "overdue-formal-06",
    contexts: ["overdue_light", "overdue_severe"],
    tones: ["formal"],
    title: "Mise en demeure",
    body: "Par la présente, {{nickname}} exige un arrosage immédiat. Retard constaté : {{daysOverdue}}j. 📜",
  },
  {
    id: "overdue-formal-07",
    contexts: ["overdue_light"],
    tones: ["formal"],
    title: "{{nickname}} — compte-rendu",
    body: "Situation : sécheresse modérée. Durée : {{daysOverdue}}j. Mesure recommandée : arrosage.",
  },
  {
    id: "overdue-formal-08",
    contexts: ["overdue_severe"],
    tones: ["formal"],
    title: "Avis urgent",
    body: "Votre {{species:lower}} {{nickname}} nécessite une intervention hydrique sans délai. {{lastWateredDays}}j.",
  },

  // --- POETIC ---
  {
    id: "overdue-poetic-01",
    contexts: ["overdue_light"],
    tones: ["poetic"],
    title: "Les jours passent",
    body: "{{daysOverdue}} tours d'horloge, et {{nickname}} attend toujours sa rosée {{plantEmoji}}",
  },
  {
    id: "overdue-poetic-02",
    contexts: ["overdue_severe"],
    tones: ["poetic"],
    title: "Désert intérieur",
    body: "Dans le silence de {{daysOverdue}}j, {{nickname}} rêve d'une pluie qui ne vient pas 🌧",
  },
  {
    id: "overdue-poetic-03",
    contexts: ["overdue_light", "overdue_severe"],
    tones: ["poetic"],
    title: "Lente sécheresse",
    body: "{{nickname}} se courbe au fil des heures. {{lastWateredDays}}j. La terre a soif, la feuille aussi.",
  },
  {
    id: "overdue-poetic-04",
    contexts: ["overdue_severe"],
    tones: ["poetic"],
    title: "Feuille par feuille",
    body: "{{nickname}} retient son souffle vert. {{daysOverdue}}j sans l'eau qui chante dans le pot 🍃",
  },
  {
    id: "overdue-poetic-05",
    contexts: ["overdue_light"],
    tones: ["poetic"],
    title: "L'attente du jardin",
    body: "Depuis {{daysOverdue}} levers de soleil, {{nickname}} patiente. Et la patience a ses limites 🌅",
  },
  {
    id: "overdue-poetic-06",
    contexts: ["overdue_severe"],
    tones: ["poetic"],
    title: "Silence végétal",
    body: "{{daysOverdue}}j que {{nickname}} chuchote à la fenêtre. Aucune réponse que le vent qui sèche.",
  },
  {
    id: "overdue-poetic-07",
    contexts: ["overdue_light", "overdue_severe"],
    tones: ["poetic"],
    title: "Chant de racines",
    body: "{{nickname}} compose un poème pour l'eau absente depuis {{daysOverdue}}j. Reviens, musique liquide.",
  },
  {
    id: "overdue-poetic-08",
    contexts: ["overdue_severe"],
    tones: ["poetic"],
    title: "Crépuscule d'une feuille",
    body: "{{nickname}} se prépare au silence. {{lastWateredDays}}j sans pluie. Les couleurs se font plus ternes.",
  },

  // --- ZEN ---
  {
    id: "overdue-zen-01",
    contexts: ["overdue_light"],
    tones: ["zen"],
    title: "{{nickname}} médite",
    body: "Sur l'absence. {{daysOverdue}}j sans eau. Tout passe. Mais un arrosage accélérerait le processus 🧘",
  },
  {
    id: "overdue-zen-02",
    contexts: ["overdue_light", "overdue_severe"],
    tones: ["zen"],
    title: "Accepter ce qui est",
    body: "{{daysOverdue}}j sans pluie intérieure. {{nickname}} respire, observe, attend. Sans jugement.",
  },
  {
    id: "overdue-zen-03",
    contexts: ["overdue_severe"],
    tones: ["zen"],
    title: "Le pot et le vide",
    body: "{{daysOverdue}}j. {{nickname}} s'exerce au détachement. Mais un peu d'eau aiderait, faut le dire.",
  },
  {
    id: "overdue-zen-04",
    contexts: ["overdue_light"],
    tones: ["zen"],
    title: "Patience infinie",
    body: "{{nickname}} attend, comme le bouddha sous l'arbre. {{daysOverdue}}j. Toi tu peux venir quand tu veux.",
  },
];
