import type { Template } from "./types";

export const WATERING_DUE_TEMPLATES: Template[] = [
  // --- FUNNY ---
  {
    id: "due-funny-01",
    contexts: ["due"],
    tones: ["funny"],
    title: "{{nickname}} a soif {{waterEmoji}}",
    body: "Coucou c'est {{nickname}}, aujourd'hui c'est officiellement le jour du verre d'eau. Rendez-vous ?",
  },
  {
    id: "due-funny-02",
    contexts: ["due"],
    tones: ["funny"],
    title: "Psst… {{nickname}}",
    body: "C'est le jour. Tu sais. L'eau. Pense à moi, même deux secondes {{plantEmoji}}",
  },
  {
    id: "due-funny-03",
    contexts: ["due"],
    tones: ["funny"],
    title: "Journée arrosage",
    body: "{{nickname}} a coché la case sur son agenda. À toi de jouer {{waterEmoji}}",
  },
  {
    id: "due-funny-04",
    contexts: ["due"],
    tones: ["funny"],
    title: "{{nickname}} passe un deal",
    body: "Toi tu m'arroses, moi je pousse. Win-win, non ? {{waterEmoji}}",
  },
  {
    id: "due-funny-05",
    contexts: ["due"],
    tones: ["funny"],
    title: "Info capitale",
    body: "C'est aujourd'hui. Le grand jour. Le JOUR de l'eau. {{nickname}} trépigne {{plantEmoji}}",
  },
  {
    id: "due-funny-06",
    contexts: ["due"],
    tones: ["funny"],
    title: "Alerte {{nickname}}",
    body: "{{nickname}} a mis son plus beau feuillage et attend son verre de {{timeOfDay}} {{waterEmoji}}",
  },
  {
    id: "due-funny-07",
    contexts: ["due"],
    tones: ["funny"],
    title: "Devine qui ?",
    body: "Indice : {{species:lower}}, verte, impatiente. Réponse : {{nickname}} 🌿",
  },
  {
    id: "due-funny-08",
    contexts: ["due"],
    tones: ["funny"],
    title: "Auto-destruction dans…",
    body: "Verser de l'eau pour annuler. Signé : {{nickname}}, ta {{species:lower}} pleine d'humour (et de soif).",
  },
  {
    id: "due-funny-09",
    contexts: ["due"],
    tones: ["funny"],
    title: "Breaking news",
    body: "{{nickname}} confirme une soif imminente. Plus de détails sur place {{waterEmoji}}",
  },
  {
    id: "due-funny-10",
    contexts: ["due"],
    tones: ["funny"],
    title: "Arrosothérapie",
    body: "Séance prévue ce {{timeOfDay}}. Patient : {{nickname}}. Traitement : eau. {{waterEmoji}}",
  },
  {
    id: "due-funny-11",
    contexts: ["due"],
    tones: ["funny"],
    title: "{{nickname}} FM",
    body: "Programme du {{timeOfDay}} : arrosage. Invité·e spécial·e : toi. Musique {{plantEmoji}}",
  },
  {
    id: "due-funny-12",
    contexts: ["due"],
    tones: ["funny"],
    title: "On est sérieux 2 min ?",
    body: "{{nickname}} a vraiment soif. Voilà. C'est dit. Merci d'avance {{waterEmoji}}",
  },
  {
    id: "due-funny-13",
    contexts: ["due"],
    tones: ["funny"],
    title: "Compte à rebours",
    body: "T-0. L'eau, maintenant. Signé : {{nickname}}, avec amour et impatience {{loveEmoji}}",
  },
  {
    id: "due-funny-14",
    contexts: ["due"],
    tones: ["funny"],
    title: "Petit service ?",
    body: "{{nickname}} propose : toi tu verses de l'eau, moi je te trouve très beau·belle aujourd'hui {{loveEmoji}}",
  },
  {
    id: "due-funny-15",
    contexts: ["due"],
    tones: ["funny"],
    title: "Menu du jour",
    body: "Entrée : de l'eau. Plat : de l'eau. Dessert : de l'eau. Signé : chef {{nickname}}",
  },
  {
    id: "due-funny-16",
    contexts: ["due"],
    tones: ["funny"],
    title: "Top moumoute {{plantEmoji}}",
    body: "Pour {{nickname}}, aujourd'hui c'est LE jour. Celui où on dit « tiens, de l'eau »",
  },
  {
    id: "due-funny-17",
    contexts: ["due"],
    tones: ["funny"],
    title: "{{nickname}} tape à la porte",
    body: "Enfin, elle peut pas, elle est dans un pot. Mais mentalement, elle tape fort {{waterEmoji}}",
  },
  {
    id: "due-funny-18",
    contexts: ["due"],
    tones: ["funny"],
    title: "Bulletin botanique",
    body: "Sécheresse confirmée dans le pot de {{nickname}}. Intervention humaine recommandée.",
  },

  // --- NEEDY ---
  {
    id: "due-needy-01",
    contexts: ["due"],
    tones: ["needy"],
    title: "Un petit verre ?",
    body: "C'est {{nickname}}. La terre est sèche, le moral aussi {{sadEmoji}} Viens me voir.",
  },
  {
    id: "due-needy-02",
    contexts: ["due"],
    tones: ["needy"],
    title: "{{nickname}} pense à toi",
    body: "Tu me manques. Et accessoirement, j'ai soif. Mais surtout tu me manques {{loveEmoji}}",
  },
  {
    id: "due-needy-03",
    contexts: ["due"],
    tones: ["needy"],
    title: "Petit SMS",
    body: "De {{nickname}} : si tu passes, j'ai soif. Si tu passes pas, j'ai soif aussi. {{loveEmoji}}",
  },
  {
    id: "due-needy-04",
    contexts: ["due"],
    tones: ["needy"],
    title: "Tu te souviens de moi ?",
    body: "C'est {{nickname}}. Ta {{species:lower}}. Celle qui t'attend sur l'étagère {{sadEmoji}}",
  },
  {
    id: "due-needy-05",
    contexts: ["due"],
    tones: ["needy"],
    title: "Demande discrète",
    body: "{{nickname}} ose à peine, mais un verre d'eau ce {{timeOfDay}}, ce serait… parfait {{loveEmoji}}",
  },
  {
    id: "due-needy-06",
    contexts: ["due"],
    tones: ["needy"],
    title: "{{nickname}} attend",
    body: "Depuis ce matin. Patiemment. Avec tendresse. Et un peu de soif. Surtout la soif.",
  },
  {
    id: "due-needy-07",
    contexts: ["due"],
    tones: ["needy"],
    title: "Coucou humain",
    body: "C'est {{nickname}}. Pense à moi stp. Juste un peu d'eau, juste un peu d'amour {{loveEmoji}}",
  },
  {
    id: "due-needy-08",
    contexts: ["due"],
    tones: ["needy"],
    title: "J'espère que tu vas bien",
    body: "Moi {{nickname}}, j'ai un peu soif, mais surtout je voulais savoir si ça va chez toi {{loveEmoji}}",
  },
  {
    id: "due-needy-09",
    contexts: ["due"],
    tones: ["needy"],
    title: "{{nickname}} pleure doucement",
    body: "Non en vrai c'est juste de la rosée. Mais ça pourrait être des larmes. Un peu d'eau ? {{sadEmoji}}",
  },
  {
    id: "due-needy-10",
    contexts: ["due"],
    tones: ["needy"],
    title: "Tu me lis ?",
    body: "{{nickname}} espère. Un petit arrosage ce {{timeOfDay}} rendrait sa journée parfaite {{loveEmoji}}",
  },

  // --- FORMAL ---
  {
    id: "due-formal-01",
    contexts: ["due"],
    tones: ["formal"],
    title: "Rappel d'arrosage",
    body: "{{nickname}} vous signale poliment que le prochain arrosage est prévu pour aujourd'hui.",
  },
  {
    id: "due-formal-02",
    contexts: ["due"],
    tones: ["formal"],
    title: "Vous prendrez bien de l'eau ?",
    body: "{{nickname}}, votre {{species}}, attend l'arrosage du jour avec la plus grande reconnaissance.",
  },
  {
    id: "due-formal-03",
    contexts: ["due"],
    tones: ["formal"],
    title: "Notification d'arrosage",
    body: "Planning : arrosage de {{nickname}} programmé ce jour. Merci de bien vouloir procéder.",
  },
  {
    id: "due-formal-04",
    contexts: ["due"],
    tones: ["formal"],
    title: "Mémo du {{timeOfDay}}",
    body: "Arrosage de {{nickname}} à effectuer. Cordialement, la direction végétale.",
  },
  {
    id: "due-formal-05",
    contexts: ["due"],
    tones: ["formal"],
    title: "Votre attention svp",
    body: "{{nickname}} ({{species}}) requiert un arrosage aujourd'hui. Bien à vous.",
  },
  {
    id: "due-formal-06",
    contexts: ["due"],
    tones: ["formal"],
    title: "{{nickname}} sollicite",
    body: "L'arrosage du {{timeOfDay}} est prévu. Merci d'avance pour votre ponctualité.",
  },

  // --- SASSY ---
  {
    id: "due-sassy-01",
    contexts: ["due"],
    tones: ["sassy"],
    title: "{{nickname}} au rapport",
    body: "RAS dans le pot, sauf que l'eau, c'est maintenant. On compte sur toi 😏",
  },
  {
    id: "due-sassy-02",
    contexts: ["due"],
    tones: ["sassy"],
    title: "Oh tiens",
    body: "{{nickname}} se rappelle à toi. Surprise, j'ai soif 😏 Tu vas faire quoi ?",
  },
  {
    id: "due-sassy-03",
    contexts: ["due"],
    tones: ["sassy"],
    title: "Alors comme ça",
    body: "On oublie {{nickname}} ? Pas grave. Juste un rappel. Amical. 🙃",
  },
  {
    id: "due-sassy-04",
    contexts: ["due"],
    tones: ["sassy"],
    title: "{{nickname}} en a assez",
    body: "De t'attendre. Un verre d'eau, ça prend 30 secondes. Hop, on s'active.",
  },
  {
    id: "due-sassy-05",
    contexts: ["due"],
    tones: ["sassy"],
    title: "T'es occupé·e ?",
    body: "Pas autant que {{nickname}} qui poireaute pour un verre d'eau depuis ce matin 😑",
  },
  {
    id: "due-sassy-06",
    contexts: ["due"],
    tones: ["sassy"],
    title: "Petit rappel",
    body: "Pour {{nickname}}, oui. Celle que t'oublies parfois. Allez, sois sympa 😤",
  },
  {
    id: "due-sassy-07",
    contexts: ["due"],
    tones: ["sassy"],
    title: "Je ne juge pas mais",
    body: "Ça fait {{lastWateredDays}}j. {{nickname}} a tout noté. Dans son petit carnet 📒",
  },
  {
    id: "due-sassy-08",
    contexts: ["due"],
    tones: ["sassy"],
    title: "Allô la Terre ?",
    body: "Ici {{nickname}}. J'ai soif. Terminé. (Tu réponds un jour ?) 😏",
  },

  // --- DRAMATIC ---
  {
    id: "due-dramatic-01",
    contexts: ["due"],
    tones: ["dramatic"],
    title: "Acte I",
    body: "{{nickname}} entre en scène. La terre est sèche. Le drame peut commencer. 🎭",
  },
  {
    id: "due-dramatic-02",
    contexts: ["due"],
    tones: ["dramatic"],
    title: "{{nickname}} prend la plume",
    body: "Si je pouvais parler, je dirais juste : l'eau. De toute mon âme chlorophyllienne.",
  },
  {
    id: "due-dramatic-03",
    contexts: ["due"],
    tones: ["dramatic"],
    title: "Le jour est venu",
    body: "{{nickname}} attend, les feuilles frémissantes d'anticipation 🌿 Que le rituel commence.",
  },
  {
    id: "due-dramatic-04",
    contexts: ["due"],
    tones: ["dramatic"],
    title: "Destin hydrique",
    body: "C'est aujourd'hui que tout se joue pour {{nickname}}. Un verre d'eau, un monde nouveau 💧",
  },

  // --- POETIC ---
  {
    id: "due-poetic-01",
    contexts: ["due"],
    tones: ["poetic"],
    title: "L'heure est venue",
    body: "Après {{lastWateredDays}}j de patience paisible, {{nickname}} tend ses racines vers toi {{plantEmoji}}",
  },
  {
    id: "due-poetic-02",
    contexts: ["due"],
    tones: ["poetic"],
    title: "Rosée attendue",
    body: "{{nickname}} rêve d'une goutte pour abreuver ses racines endormies {{plantEmoji}}",
  },
  {
    id: "due-poetic-03",
    contexts: ["due"],
    tones: ["poetic"],
    title: "Septième jour",
    body: "Comme convenu, {{nickname}} accueille l'eau après {{frequencyDays}} jours d'attente sereine.",
  },
  {
    id: "due-poetic-04",
    contexts: ["due"],
    tones: ["poetic"],
    title: "Gouttelette",
    body: "Voici venu le temps pour {{nickname}} de boire la vie, goutte à goutte 💧",
  },
  {
    id: "due-poetic-05",
    contexts: ["due"],
    tones: ["poetic"],
    title: "Petit matin",
    body: "{{nickname}} ouvre ses feuilles à la lumière, attendant patiemment la pluie intérieure.",
  },

  // --- ZEN ---
  {
    id: "due-zen-01",
    contexts: ["due"],
    tones: ["zen"],
    title: "Petit rituel",
    body: "Ce {{timeOfDay}}, {{nickname}} aimerait bien son verre d'eau. Rien de plus {{plantEmoji}}",
  },
  {
    id: "due-zen-02",
    contexts: ["due"],
    tones: ["zen"],
    title: "Souffle et arrose",
    body: "{{nickname}} t'attend avec sérénité pour le moment hydratation. Prends ton temps.",
  },
  {
    id: "due-zen-03",
    contexts: ["due"],
    tones: ["zen"],
    title: "Moment présent",
    body: "Ici, maintenant : une {{species:lower}} qui a besoin d'eau. C'est tout. Et c'est beau.",
  },
  {
    id: "due-zen-04",
    contexts: ["due"],
    tones: ["zen"],
    title: "Flux d'eau",
    body: "{{nickname}} aimerait bien son verre ce {{timeOfDay}}. Tout vient à qui sait attendre {{plantEmoji}}",
  },
  {
    id: "due-zen-05",
    contexts: ["due"],
    tones: ["zen"],
    title: "Respire",
    body: "{{nickname}} aussi. Et là, elle aimerait un peu d'eau. Ensemble on respire, ensemble on vit.",
  },

  // --- WORRIED ---
  {
    id: "due-worried-01",
    contexts: ["due"],
    tones: ["worried"],
    title: "Petite inquiétude",
    body: "{{nickname}} commence à avoir la gorge sèche. Tu penses à l'eau ?",
  },
  {
    id: "due-worried-02",
    contexts: ["due"],
    tones: ["worried"],
    title: "Ça va ?",
    body: "{{nickname}} commence à moins aller. Un verre d'eau et tout ira mieux {{waterEmoji}}",
  },
  {
    id: "due-worried-03",
    contexts: ["due"],
    tones: ["worried"],
    title: "{{nickname}} s'inquiète",
    body: "{{lastWateredDays}}j sans une goutte. Pas catastrophique, mais bon. Tu viens ?",
  },
  {
    id: "due-worried-04",
    contexts: ["due"],
    tones: ["worried"],
    title: "Hmm…",
    body: "{{nickname}} aimerait juste s'assurer qu'on pense toujours à elle. Un verre suffira {{loveEmoji}}",
  },
];
